/*
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FSMAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/gemoc/course/fsm/xtext/parser/antlr/internal/InternalFSM.tokens");
	}
}
