/**
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.gemoc.course.fsm.xtext.ui.AbstractFSMUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FSMUiModule extends AbstractFSMUiModule {
  public FSMUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
