/**
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.tests;

import com.google.inject.Inject;
import fsm.FiniteStateMachine;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.gemoc.course.fsm.xtext.tests.FSMInjectorProvider;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(FSMInjectorProvider.class)
@SuppressWarnings("all")
public class FSMParsingTest {
  @Inject
  private ParseHelper<FiniteStateMachine> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final FiniteStateMachine result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
