/**
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.ui.contentassist;

import org.gemoc.course.fsm.xtext.ui.contentassist.AbstractFSMProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FSMProposalProvider extends AbstractFSMProposalProvider {
}
