/**
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.scoping;

import org.gemoc.course.fsm.xtext.scoping.AbstractFSMScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class FSMScopeProvider extends AbstractFSMScopeProvider {
}
