/**
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.validation;

import org.gemoc.course.fsm.xtext.validation.AbstractFSMValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FSMValidator extends AbstractFSMValidator {
}
