/*
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FSMStandaloneSetup extends FSMStandaloneSetupGenerated {

	def static void doSetup() {
		new FSMStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
