/**
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext;

import org.gemoc.course.fsm.xtext.AbstractFSMRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FSMRuntimeModule extends AbstractFSMRuntimeModule {
}
