/*
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.gemoc.course.fsm.xtext.ui.internal.XtextActivator;

public class FSMUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.gemoc.course.fsm.xtext.FSM");
	}

}
