/*
 * generated by Xtext 2.10.0
 */
package org.gemoc.course.fsm.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFSMScopeProvider extends DelegatingScopeProvider {
}
